--TABLE USER
CREATE TABLE USERR(
ID_TAIKHOAN NVARCHAR(10) PRIMARY KEY ,
TENKHACHHANG NVARCHAR(20) ,
GIOITINH BIT ,
SDT INT ,
EMAIL NVARCHAR(50) )

--TABLE TAIKHOAN
CREATE TABLE TAIKHOAN(
ID_TAIKHOAN NVARCHAR(10) PRIMARY KEY,
USERNAME NVARCHAR(20),
PASSWORK NVARCHAR(50),
LOAI_USER NVARCHAR(20)
CONSTRAINT RB_KHOAUSER FOREIGN KEY(ID_TAIKHOAN) REFERENCES USERR(ID_TAIKHOAN))

--TABLE LOAITIN
CREATE TABLE LOAITIN(
ID_TIN NVARCHAR(10) PRIMARY KEY,
LOAITIN NVARCHAR(20))


--table đánh giá 
CREATE TABLE DANHGIA(
ID_TAIKHOAN NVARCHAR(10) PRIMARY KEY,
DANHGIATIN NVARCHAR,
DANHGIATRO NVARCHAR,
--CONSTRAINT RB_KHOADG PRIMARY KEY (ID_TAIKHOAN, ID_DANHGIA),
CONSTRAINT RB_USER FOREIGN KEY (ID_TAIKHOAN) REFERENCES USERR(ID_TAIKHOAN)
)

--TABLE BAIDANG
CREATE TABLE BAIDANG(
ID_TAIKHOAN NVARCHAR(10),
ID_TIN NVARCHAR(10),
NOIDUNGTIN NVARCHAR(MAX),
NGAYDANG DATETIME ,
GIA FLOAT,
TIEUDE NVARCHAR(MAX),
CONSTRAINT RB_KHOA PRIMARY KEY(ID_TAIKHOAN, ID_TIN),
CONSTRAINT RB_KHOATK FOREIGN KEY(ID_TAIKHOAN) REFERENCES TAIKHOAN(ID_TAIKHOAN),
CONSTRAINT RB_KHOALOAITIN FOREIGN KEY(ID_TIN) REFERENCES LOAITIN(ID_TIN),
CONSTRAINT RB_DG FOREIGN KEY (ID_TAIKHOAN) REFERENCES DANHGIA(ID_TAIKHOAN)

)








